services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./Tracks:/app/Tracks
      - node_modules:/app/node_modules

volumes:
  node_modules:
